using FluentAssertions;
using Rapicgen.Core.Options.Refitter;
using Xunit;

namespace ApiClientCodeGen.Core.Tests.Options;

public class DefaultRefitterOptionsTests
{
    private readonly IRefitterOptions sut = new DefaultRefitterOptions();

    [Fact]
    public void GenerateContracts_DefaultTrue()
        => sut.GenerateContracts.Should().BeTrue();

    [Fact]
    public void GenerateXmlDocCodeComments_DefaultTrue()
        => sut.GenerateXmlDocCodeComments.Should().BeTrue();

    [Fact]
    public void AddAutoGeneratedHeader_DefaultFalse()
        => sut.AddAutoGeneratedHeader.Should().BeFalse();

    [Fact]
    public void ReturnIApiResponse_DefaultFalse()
        => sut.ReturnIApiResponse.Should().BeFalse();

    [Fact]
    public void GenerateInternalTypes_DefaultFalse()
        => sut.GenerateInternalTypes.Should().BeFalse();

    [Fact]
    public void UseCancellationTokens_DefaultFalse()
        => sut.UseCancellationTokens.Should().BeFalse();

    [Fact]
    public void GenerateHeaderParameters_DefaultTrue()
        => sut.GenerateHeaderParameters.Should().BeTrue();

    [Fact]
    public void GenerateMultipleFiles_DefaultFalse()
        => sut.GenerateMultipleFiles.Should().BeFalse();
}
