using System;
using System.IO;
using Rapicgen.Core.Installer;
using Rapicgen.Core.Logging;
using Rapicgen.Core.Options.NSwag;

namespace Rapicgen.Core.Generators.NSwag
{
    public class NSwagCSharpCodeGenerator : ICodeGenerator
    {
        private readonly string swaggerFile;
        private readonly string defaultNamespace;
        private readonly INSwagOptions options;
        private readonly IProcessLauncher processLauncher;
        private readonly IDependencyInstaller dependencyInstaller;

        public NSwagCSharpCodeGenerator(
            string swaggerFile,
            string defaultNamespace,
            INSwagOptions options,
            IProcessLauncher processLauncher,
            IDependencyInstaller dependencyInstaller)
        {
            this.swaggerFile = swaggerFile;
            this.defaultNamespace = defaultNamespace;
            this.options = options ?? throw new ArgumentNullException(nameof(options));
            this.processLauncher = processLauncher ?? throw new ArgumentNullException(nameof(processLauncher));
            this.dependencyInstaller = dependencyInstaller ?? throw new ArgumentNullException(nameof(dependencyInstaller));
        }

        public string GenerateCode(IProgressReporter? pGenerateProgress)
        {
            pGenerateProgress?.Progress(10);
            dependencyInstaller.InstallNSwag();
            pGenerateProgress?.Progress(30);

            var outputPath = Path.Combine(Path.GetTempPath(), Guid.NewGuid().ToString() + ".cs");
            var arguments = BuildArguments(swaggerFile, outputPath);

            using var context = new DependencyContext("NSwag", $"nswag {arguments}");
            processLauncher.Start("nswag", arguments, Path.GetDirectoryName(swaggerFile)!);
            context.Succeeded();

            pGenerateProgress?.Progress(80);

            string generatedCode = string.Empty;
            if (File.Exists(outputPath))
            {
                generatedCode = File.ReadAllText(outputPath);
                File.Delete(outputPath);
            }

            pGenerateProgress?.Progress(100);
            return GeneratedCode.PrefixAutogeneratedCodeHeader(generatedCode, "NSwag", "v14.4.0");
        }

        private string BuildArguments(string inputFile, string outputPath)
        {
            var args = $"openapi2csclient /input:\"{inputFile}\" /output:\"{outputPath}\"";
            
            if (!string.IsNullOrEmpty(defaultNamespace))
            {
                args += $" /namespace:\"{defaultNamespace}\"";
            }

            if (!options.UseDocumentTitle)
            {
                 var className = Path.GetFileNameWithoutExtension(inputFile);
                 className = className.Replace(" ", "").Replace(".", "").Replace("-", "") + "Client";
                 args += $" /className:\"{className}\"";
            }

            args += $" /InjectHttpClient:{options.InjectHttpClient.ToString().ToLower()}";
            args += $" /GenerateClientInterfaces:{options.GenerateClientInterfaces.ToString().ToLower()}";
            args += $" /GenerateDtoTypes:{options.GenerateDtoTypes.ToString().ToLower()}";
            args += $" /UseBaseUrl:{options.UseBaseUrl.ToString().ToLower()}";
            
            if (!string.IsNullOrEmpty(options.ParameterDateTimeFormat))
            {
                args += $" /ParameterDateTimeFormat:\"{options.ParameterDateTimeFormat}\"";
            }
            
            if (!string.IsNullOrEmpty(options.ClassStyle))
            {
                args += $" /ClassStyle:{options.ClassStyle}";
            }

            return args;
        }
    }
}
