using System;
using System.IO;
using Rapicgen.Core.Installer;
using Rapicgen.Core.Logging;
using Rapicgen.Core.Options.NSwag;

namespace Rapicgen.Core.Generators.NSwag
{
    public class NSwagCSharpCodeGenerator : ICodeGenerator
    {
        private readonly string swaggerFile;
        private readonly string defaultNamespace;
        private readonly IProcessLauncher processLauncher;
        private readonly IDependencyInstaller dependencyInstaller;
        private readonly INSwagOptions options;

        private const string Command = "nswag";

        public NSwagCSharpCodeGenerator(
            string swaggerFile,
            string defaultNamespace,
            IProcessLauncher processLauncher,
            IDependencyInstaller dependencyInstaller,
            INSwagOptions options)
        {
            this.swaggerFile = swaggerFile ?? throw new ArgumentNullException(nameof(swaggerFile));
            this.defaultNamespace = defaultNamespace ?? throw new ArgumentNullException(nameof(defaultNamespace));
            this.processLauncher = processLauncher ?? throw new ArgumentNullException(nameof(processLauncher));
            this.dependencyInstaller = dependencyInstaller ?? throw new ArgumentNullException(nameof(dependencyInstaller));
            this.options = options ?? throw new ArgumentNullException(nameof(options));
        }

        public string GenerateCode(IProgressReporter? pGenerateProgress)
        {
            pGenerateProgress?.Progress(10);
            dependencyInstaller.InstallNSwag();

            pGenerateProgress?.Progress(30);
            var outputPath = Path.Combine(Path.GetTempPath(), Guid.NewGuid() + ".cs");
            var workingDirectory = Path.GetDirectoryName(swaggerFile);
            var className = GenerateClassName(swaggerFile);

            pGenerateProgress?.Progress(40);
            var arguments = BuildNSwagArguments(outputPath, className);

            using var context = new DependencyContext("NSwag", $"{Command} {arguments}");
            processLauncher.Start(Command, arguments, workingDirectory);
            context.Succeeded();

            pGenerateProgress?.Progress(80);

            string generatedCode = string.Empty;
            if (File.Exists(outputPath))
            {
                generatedCode = File.ReadAllText(outputPath);
                File.Delete(outputPath);
            }

            pGenerateProgress?.Progress(100);
            return GeneratedCode.PrefixAutogeneratedCodeHeader(generatedCode, "NSwag", "v14.4.0");
        }

        private string BuildNSwagArguments(string outputPath, string className)
        {
            var classStyle = options.ClassStyle.ToString();
            
            var args = $"openapi2csclient " +
                       $"/input:\"{swaggerFile}\" " +
                       $"/output:\"{outputPath}\" " +
                       $"/namespace:{defaultNamespace} " +
                       $"/ClassName:{className} " +
                       $"/InjectHttpClient:{options.InjectHttpClient.ToString().ToLowerInvariant()} " +
                       $"/GenerateClientInterfaces:{options.GenerateClientInterfaces.ToString().ToLowerInvariant()} " +
                       $"/GenerateDtoTypes:{options.GenerateDtoTypes.ToString().ToLowerInvariant()} " +
                       $"/UseBaseUrl:{options.UseBaseUrl.ToString().ToLowerInvariant()} " +
                       $"/ClassStyle:{classStyle} " +
                       $"/ParameterDateTimeFormat:\"{options.ParameterDateTimeFormat}\"";

            return args;
        }

        private string GenerateClassName(string filePath)
        {
            var fileInfo = new FileInfo(filePath);
            if (options.UseDocumentTitle)
            {
                // When using document title, we let NSwag determine the class name
                // But we need to provide a default - we'll use the filename as fallback
                var name = fileInfo.Name
                    .Replace(".json", string.Empty)
                    .Replace(".yaml", string.Empty)
                    .Replace(".yml", string.Empty)
                    .Replace(".", string.Empty)
                    .Replace("-", string.Empty)
                    .Replace(" ", string.Empty);
                return string.IsNullOrWhiteSpace(name) ? "ApiClient" : $"{name}Client";
            }

            var fileName = fileInfo.Name
                .Replace(".json", string.Empty)
                .Replace(".yaml", string.Empty)
                .Replace(".yml", string.Empty)
                .Replace(".", string.Empty)
                .Replace("-", string.Empty)
                .Replace(" ", string.Empty);

            return string.IsNullOrWhiteSpace(fileName) ? "ApiClient" : fileName;
        }
    }
}