using FluentAssertions;
using Rapicgen.Core.Generators;
using Xunit;

namespace ApiClientCodeGen.Core.Tests.Generators;

public class GeneratedCodeAdditionalTests
{
    [Fact]
    public void PrefixAutogeneratedCodeHeader_ContainsClosingTag()
    {
        var result = GeneratedCode.PrefixAutogeneratedCodeHeader("code", "NSwag", "1.0");

        result.Should().Contain("</auto-generated>");
    }

    [Fact]
    public void PrefixAutogeneratedCodeHeader_ContainsOriginalCode()
    {
        const string code = "public class MyApi { }";
        var result = GeneratedCode.PrefixAutogeneratedCodeHeader(code, "NSwag", "1.0");

        result.Should().Contain(code);
    }

    [Fact]
    public void PrefixAutogeneratedCodeHeader_ContainsGeneratorLabel()
    {
        var result = GeneratedCode.PrefixAutogeneratedCodeHeader("code", "TestTool", "2.0");

        result.Should().Contain("Generated REST API Client Code Generator");
    }

    [Fact]
    public void PrefixAutogeneratedCodeHeader_WithNullVersion_DoesNotThrow()
    {
        var result = GeneratedCode.PrefixAutogeneratedCodeHeader("code", "NSwag");

        result.Should().Contain("NSwag");
        result.Should().Contain("<auto-generated>");
    }

    [Fact]
    public void PrefixAutogeneratedCodeHeader_WithEmptyCode_ReturnsHeaderOnly()
    {
        var result = GeneratedCode.PrefixAutogeneratedCodeHeader(string.Empty, "TestTool", "1.0");

        result.Should().Contain("<auto-generated>");
        result.Should().Contain("TestTool");
    }

    [Fact]
    public void PrefixAutogeneratedCodeHeader_HeaderAppearsBeforeCode()
    {
        const string code = "namespace MyApp { }";
        var result = GeneratedCode.PrefixAutogeneratedCodeHeader(code, "NSwag", "1.0");

        var headerIndex = result.IndexOf("<auto-generated>");
        var codeIndex = result.IndexOf(code);

        headerIndex.Should().BeLessThan(codeIndex);
    }

    [Fact]
    public void PrefixAutogeneratedCodeHeader_ContainsAssemblyVersion()
    {
        var result = GeneratedCode.PrefixAutogeneratedCodeHeader("code", "NSwag", "1.0");
        var version = typeof(GeneratedCode).Assembly.GetName().Version;

        result.Should().Contain(version!.ToString());
    }
}
