using System;
using Rapicgen.Core.Logging;
using Rapicgen.Core.Options.Refitter;

namespace Rapicgen.Options.Refitter
{
    public class RefitterCSharpOptions
        : OptionsBase<IRefitterOptions, RefitterOptionsPage>, IRefitterOptions
    {
        public RefitterCSharpOptions(IRefitterOptions? options = null)
        {
            try
            {
                options ??= GetFromDialogPage();

                GenerateContracts = options.GenerateContracts;
                GenerateXmlDocCodeComments = options.GenerateXmlDocCodeComments;
                AddAutoGeneratedHeader = options.AddAutoGeneratedHeader;
                ReturnIApiResponse = options.ReturnIApiResponse;
            }
            catch (Exception e)
            {
                Logger.Instance.TrackError(e);

                GenerateContracts = true;
                GenerateXmlDocCodeComments = true;
                AddAutoGeneratedHeader = true;
            }
        }

        public bool GenerateContracts { get; set; }
        public bool GenerateXmlDocCodeComments { get; set; }
        public bool AddAutoGeneratedHeader { get; set; }
        public bool ReturnIApiResponse { get; set; }
    }
}