
// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Usage", "VSTHRD002:Avoid problematic synchronous waits", Justification = "<Pending>", Scope = "member", Target = "~M:ChristianHelle.DeveloperTools.CodeGenerators.ApiClient.IntegrationTests.VisualBasic.AutoRestVisualBasicCodeGeneratorTests.Init(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext)")]
[assembly: SuppressMessage("Style", "VSTHRD200:Use \"Async\" suffix for async methods", Justification = "<Pending>", Scope = "member", Target = "~M:ChristianHelle.DeveloperTools.CodeGenerators.ApiClient.IntegrationTests.Generators.NSwagStudioCodeGeneratorTests.NSwagStudio_Generate_Code_Using_NSwagStudio_From_SwaggerSpec~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Usage", "VSTHRD010:Use VS services from UI thread", Justification = "<Pending>", Scope = "member", Target = "~M:ChristianHelle.DeveloperTools.CodeGenerators.ApiClient.IntegrationTests.CustomTool.CSharpSingleFileCodeGeneratorTests.Assert(ChristianHelle.DeveloperTools.CodeGenerators.ApiClient.Core.SupportedCodeGenerator,ChristianHelle.DeveloperTools.CodeGenerators.ApiClient.Options.IOptionsFactory)")]
[assembly: SuppressMessage("Usage", "VSTHRD010:Use VS services from UI thread", Justification = "<Pending>", Scope = "member", Target = "~M:ChristianHelle.DeveloperTools.CodeGenerators.ApiClient.IntegrationTests.Generators.AutoRestCodeGeneratorTests.AutoRest_CSharp_Reports_Progres")]
[assembly: SuppressMessage("Usage", "VSTHRD002:Avoid problematic synchronous waits", Justification = "<Pending>", Scope = "member", Target = "~M:ChristianHelle.DeveloperTools.CodeGenerators.ApiClient.IntegrationTests.Generators.NSwagStudioCodeGeneratorBuildTests.Init(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext)")]
[assembly: SuppressMessage("Usage", "VSTHRD010:Use VS services from UI thread", Justification = "<Pending>", Scope = "member", Target = "~M:ChristianHelle.DeveloperTools.CodeGenerators.ApiClient.IntegrationTests.VisualBasic.AutoRestVisualBasicCodeGeneratorTests.AutoRest_Reports_Progres")]
[assembly: SuppressMessage("Usage", "VSTHRD010:Use VS services from UI thread", Justification = "<Pending>", Scope = "member", Target = "~M:ChristianHelle.DeveloperTools.CodeGenerators.ApiClient.IntegrationTests.Generators.OpenApiCodeGeneratorTests.OpenApi_Reports_Progres")]
[assembly: SuppressMessage("Style", "VSTHRD200:Use \"Async\" suffix for async methods", Justification = "<Pending>", Scope = "member", Target = "~M:ChristianHelle.DeveloperTools.CodeGenerators.ApiClient.IntegrationTests.VisualBasic.NSwagStudioVisualBasicCodeGeneratorTests.NSwagStudio_Generate_Code_Using_NSwagStudio~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Usage", "VSTHRD010:Use VS services from UI thread", Justification = "<Pending>", Scope = "member", Target = "~M:ChristianHelle.DeveloperTools.CodeGenerators.ApiClient.IntegrationTests.VisualBasic.SwaggerVisualBasicCodeGeneratorTests.Swagger_Reports_Progres")]
[assembly: SuppressMessage("Usage", "VSTHRD010:Use VS services from UI thread", Justification = "<Pending>", Scope = "member", Target = "~M:ChristianHelle.DeveloperTools.CodeGenerators.ApiClient.IntegrationTests.VisualBasic.NSwagVisualBasicCodeGeneratorTests.NSwag_Reports_Progres")]
[assembly: SuppressMessage("Usage", "VSTHRD010:Use VS services from UI thread", Justification = "<Pending>", Scope = "member", Target = "~M:ChristianHelle.DeveloperTools.CodeGenerators.ApiClient.IntegrationTests.VisualBasic.OpenApiVisualBasicCodeGeneratorTests.OpenApi_Reports_Progres")]
[assembly: SuppressMessage("Usage", "VSTHRD010:Use VS services from UI thread", Justification = "<Pending>", Scope = "member", Target = "~M:ChristianHelle.DeveloperTools.CodeGenerators.ApiClient.IntegrationTests.CustomTool.VisualBasicSingleFileCodeGeneratorTests.Assert(ChristianHelle.DeveloperTools.CodeGenerators.ApiClient.Core.SupportedCodeGenerator,ChristianHelle.DeveloperTools.CodeGenerators.ApiClient.Options.IOptionsFactory)")]
[assembly: SuppressMessage("Usage", "VSTHRD010:Use VS services from UI thread", Justification = "<Pending>", Scope = "member", Target = "~M:ChristianHelle.DeveloperTools.CodeGenerators.ApiClient.IntegrationTests.Generators.NSwagCodeGeneratorTests.NSwag_Reports_Progres")]
[assembly: SuppressMessage("Usage", "VSTHRD010:Use VS services from UI thread", Justification = "<Pending>", Scope = "member", Target = "~M:ChristianHelle.DeveloperTools.CodeGenerators.ApiClient.IntegrationTests.Generators.SwaggerCodeGeneratorTests.Swagger_Reports_Progres")]

