//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rapicgen.Core {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Rapicgen.Core.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://repo1.maven.org/maven2/org/openapitools/openapi-generator-cli/6.0.1/openapi-generator-cli-6.0.1.jar.
        /// </summary>
        public static string LegacyOpenApiGenerator_DownloadUrl {
            get {
                return ResourceManager.GetString("LegacyOpenApiGenerator_DownloadUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACE9D0D6F89AFED9EED414DCB3736DFABC911B77.
        /// </summary>
        public static string LegacyOpenApiGenerator_SHA1 {
            get {
                return ResourceManager.GetString("LegacyOpenApiGenerator_SHA1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://repo1.maven.org/maven2/org/openapitools/openapi-generator-cli/7.12.0/openapi-generator-cli-7.12.0.jar.
        /// </summary>
        public static string OpenApiGenerator_DownloadUrl {
            get {
                return ResourceManager.GetString("OpenApiGenerator_DownloadUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 40770e424b885e5878471d4a19ba951b.
        /// </summary>
        public static string OpenApiGenerator_MD5 {
            get {
                return ResourceManager.GetString("OpenApiGenerator_MD5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2c7d5141384d2caaa2d11d370ed172525855c157.
        /// </summary>
        public static string OpenApiGenerator_SHA1 {
            get {
                return ResourceManager.GetString("OpenApiGenerator_SHA1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://repo1.maven.org/maven2/io/swagger/codegen/v3/swagger-codegen-cli/3.0.34/swagger-codegen-cli-3.0.34.jar.
        /// </summary>
        public static string SwaggerCodegenCli_DownloadUrl {
            get {
                return ResourceManager.GetString("SwaggerCodegenCli_DownloadUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A91658FA5F85D8501D0FB5E4501D35CF.
        /// </summary>
        public static string SwaggerCodegenCli_MD5 {
            get {
                return ResourceManager.GetString("SwaggerCodegenCli_MD5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 54EB5F2561C77D23AF3FA2E4CEA8A100BA8F71C8.
        /// </summary>
        public static string SwaggerCodegenCli_SHA1 {
            get {
                return ResourceManager.GetString("SwaggerCodegenCli_SHA1", resourceCulture);
            }
        }
    }
}
