namespace Rapicgen.Core.Options.Refitter;

public class DefaultRefitterOptions : IRefitterOptions
{
    public bool GenerateContracts { get; set; } = true;
    public bool GenerateXmlDocCodeComments { get; set; } = true;
    public bool AddAutoGeneratedHeader { get; set; }
    public bool ReturnIApiResponse { get; set; }
}