using System.Diagnostics.CodeAnalysis;

namespace Rapicgen.Core.Options.Refitter;

[ExcludeFromCodeCoverage]
public class DefaultRefitterOptions : IRefitterOptions
{
    public bool GenerateContracts { get; set; } = true;
    public bool GenerateXmlDocCodeComments { get; set; } = true;
    public bool AddAutoGeneratedHeader { get; set; }
    public bool ReturnIApiResponse { get; set; }
    public bool GenerateInternalTypes { get; set; }
    public bool UseCancellationTokens { get; set; }
    public bool GenerateHeaderParameters { get; set; } = true;
    public bool GenerateMultipleFiles { get; set; }
}