namespace Rapicgen.Core.Options.Refitter
{
    public interface IRefitterOptions
    {
        bool GenerateContracts { get; set; }
        bool GenerateXmlDocCodeComments { get; set; }
        bool AddAutoGeneratedHeader { get; set; }
        bool ReturnIApiResponse { get; set; }
        bool GenerateInternalTypes { get; set; }
        bool UseCancellationTokens { get; set; }
        bool GenerateHeaderParameters { get; set; }
        bool GenerateMultipleFiles { get; set; }
    }
}