using System;

namespace Rapicgen.Core.Generators;

public static class GeneratedCode
{
    public static string PrefixAutogeneratedCodeHeader(string code, string toolName, string? toolVersion = null)
    {
        var header = $"""
//----------------------
// <auto-generated>
//     Generated REST API Client Code Generator v{typeof(GeneratedCode).Assembly.GetName().Version} on {DateTime.Now}
//     Using the tool {toolName} {toolVersion}
// </auto-generated>
//----------------------
""";
        return $"{header}{Environment.NewLine}{Environment.NewLine}{code}";
    }
}