using System.IO;
using FluentAssertions;
using Moq;
using Rapicgen.Core;
using Rapicgen.Core.Generators;
using Rapicgen.Core.Generators.Refitter;
using Rapicgen.Core.Installer;
using Rapicgen.Core.Options.Refitter;
using Xunit;

namespace ApiClientCodeGen.Core.Tests.Generators.Refitter;

public class RefitterCodeGeneratorTests
{
    [Fact]
    public void BuildRefitterArguments_With_MultipleFiles_Includes_Flag()
    {
        var swaggerFile = Path.Combine(Path.GetTempPath(), "test.json");
        File.WriteAllText(swaggerFile, "{}");

        try
        {
            var options = new Mock<IRefitterOptions>();
            options.Setup(o => o.GenerateMultipleFiles).Returns(true);
            options.Setup(o => o.GenerateContracts).Returns(true);
            options.Setup(o => o.GenerateXmlDocCodeComments).Returns(true);
            options.Setup(o => o.GenerateHeaderParameters).Returns(true);
            options.Setup(o => o.AddAutoGeneratedHeader).Returns(true);

            var processLauncher = new Mock<IProcessLauncher>();
            var dependencyInstaller = new Mock<IDependencyInstaller>();

            var sut = new RefitterCodeGenerator(
                swaggerFile,
                "TestNamespace",
                processLauncher.Object,
                dependencyInstaller.Object,
                options.Object);

            sut.GenerateCode(null);

            processLauncher.Verify(
                p => p.Start(
                    "refitter",
                    It.Is<string>(s => s.Contains("--multiple-files")),
                    It.IsAny<string>()),
                Times.Once);
        }
        finally
        {
            if (File.Exists(swaggerFile))
                File.Delete(swaggerFile);
        }
    }

    [Fact]
    public void BuildRefitterArguments_Without_MultipleFiles_Does_Not_Include_Flag()
    {
        var swaggerFile = Path.Combine(Path.GetTempPath(), "test.json");
        File.WriteAllText(swaggerFile, "{}");

        try
        {
            var options = new Mock<IRefitterOptions>();
            options.Setup(o => o.GenerateMultipleFiles).Returns(false);
            options.Setup(o => o.GenerateContracts).Returns(true);
            options.Setup(o => o.GenerateXmlDocCodeComments).Returns(true);
            options.Setup(o => o.GenerateHeaderParameters).Returns(true);
            options.Setup(o => o.AddAutoGeneratedHeader).Returns(true);

            var processLauncher = new Mock<IProcessLauncher>();
            var dependencyInstaller = new Mock<IDependencyInstaller>();

            var sut = new RefitterCodeGenerator(
                swaggerFile,
                "TestNamespace",
                processLauncher.Object,
                dependencyInstaller.Object,
                options.Object);

            sut.GenerateCode(null);

            processLauncher.Verify(
                p => p.Start(
                    "refitter",
                    It.Is<string>(s => !s.Contains("--multiple-files")),
                    It.IsAny<string>()),
                Times.Once);
        }
        finally
        {
            if (File.Exists(swaggerFile))
                File.Delete(swaggerFile);
        }
    }

    [Fact]
    public void GenerateFromSwaggerFile_With_MultipleFiles_Returns_EmptyString()
    {
        var swaggerFile = Path.Combine(Path.GetTempPath(), "test.json");
        File.WriteAllText(swaggerFile, "{}");

        try
        {
            var options = new Mock<IRefitterOptions>();
            options.Setup(o => o.GenerateMultipleFiles).Returns(true);
            options.Setup(o => o.GenerateContracts).Returns(true);
            options.Setup(o => o.GenerateXmlDocCodeComments).Returns(true);
            options.Setup(o => o.GenerateHeaderParameters).Returns(true);
            options.Setup(o => o.AddAutoGeneratedHeader).Returns(true);

            var processLauncher = new Mock<IProcessLauncher>();
            var dependencyInstaller = new Mock<IDependencyInstaller>();

            var sut = new RefitterCodeGenerator(
                swaggerFile,
                "TestNamespace",
                processLauncher.Object,
                dependencyInstaller.Object,
                options.Object);

            var result = sut.GenerateCode(null);

            result.Should().BeEmpty();
        }
        finally
        {
            if (File.Exists(swaggerFile))
                File.Delete(swaggerFile);
        }
    }

    [Fact]
    public void GenerateFromSwaggerFile_With_MultipleFiles_Uses_Directory_As_Output()
    {
        var swaggerFile = Path.Combine(Path.GetTempPath(), "test.json");
        File.WriteAllText(swaggerFile, "{}");

        try
        {
            var options = new Mock<IRefitterOptions>();
            options.Setup(o => o.GenerateMultipleFiles).Returns(true);
            options.Setup(o => o.GenerateContracts).Returns(true);
            options.Setup(o => o.GenerateXmlDocCodeComments).Returns(true);
            options.Setup(o => o.GenerateHeaderParameters).Returns(true);
            options.Setup(o => o.AddAutoGeneratedHeader).Returns(true);

            var processLauncher = new Mock<IProcessLauncher>();
            var dependencyInstaller = new Mock<IDependencyInstaller>();

            var sut = new RefitterCodeGenerator(
                swaggerFile,
                "TestNamespace",
                processLauncher.Object,
                dependencyInstaller.Object,
                options.Object);

            sut.GenerateCode(null);

            var expectedDir = Path.GetTempPath().TrimEnd(Path.DirectorySeparatorChar);
            processLauncher.Verify(
                p => p.Start(
                    "refitter",
                    It.Is<string>(s =>
                        s.Contains("--multiple-files") &&
                        s.Contains($"--output \"{expectedDir}\"")),
                    It.IsAny<string>()),
                Times.Once);
        }
        finally
        {
            if (File.Exists(swaggerFile))
                File.Delete(swaggerFile);
        }
    }
}
