using Microsoft.VisualStudio.Extensibility;
using Microsoft.VisualStudio.Extensibility.Commands;
using NSwag.CodeGeneration.CSharp;
using Rapicgen.Core;
using Rapicgen.Core.Generators;
using Rapicgen.Core.Generators.NSwag;
using Rapicgen.Core.Logging;
using Rapicgen.Core.Options.NSwag;
using System.Diagnostics;

namespace ApiClientCodeGen.VSIX.Extensibility.Commands;

[VisualStudioContribution]
public class GenerateNSwagCommand(TraceSource traceSource) : Command
{
    public override CommandConfiguration CommandConfiguration => new("%NSwagCommand.DisplayName%")
    {
        Icon = new(ImageMoniker.KnownValues.Extension, IconSettings.IconAndText),
        VisibleWhen = ActivationConstraint.ClientContext(ClientContextKey.Shell.ActiveSelectionFileName, ".(json|ya?ml)")
    };

    public override async Task ExecuteCommandAsync(IClientContext context, CancellationToken cancellationToken)
    {
        Logger.Instance.TrackFeatureUsage("Generate NSwag output");

        var inputFile = await context.GetInputFileAsync(cancellationToken);
        var namespaceName = await context.GetDefaultNamespaceAsync(cancellationToken);

        using var dependencyContext = new DependencyContext("NSwag");
        try
        {
            var documentFactory = new OpenApiDocumentFactory();
            var document = await documentFactory.GetDocumentAsync(inputFile);

            var generatorSettingsFactory = new NSwagCodeGeneratorSettingsFactory(
                namespaceName,
                new DefaultNSwagOptions());

            var settings = generatorSettingsFactory.GetGeneratorSettings(document);
            var generator = new CSharpClientGenerator(document, settings);
            var csharpCode = generator.GenerateFile();

            csharpCode = GeneratedCode.PrefixAutogeneratedCodeHeader(csharpCode, "NSwag", "v14.6.0");
            if (csharpCode is not null)
            {
                await File.WriteAllTextAsync(
                    inputFile.Replace(new FileInfo(inputFile).Extension, ".cs"),
                    csharpCode,
                    cancellationToken);
            }
        }
        catch (Exception e)
        {
            traceSource.TraceEvent(TraceEventType.Error, 0, $"Error generating NSwag code: {e}");
        }
        finally
        {
            dependencyContext.Succeeded();
        }
    }
}
