using Microsoft.VisualStudio.Extensibility;
using Microsoft.VisualStudio.Extensibility.Commands;
using NSwag.CodeGeneration.CSharp;
using Rapicgen.Core;
using Rapicgen.Core.Generators;
using Rapicgen.Core.Generators.NSwag;
using Rapicgen.Core.Logging;
using Rapicgen.Core.Options.NSwag;
using System.Diagnostics;
using System.Text.Json;

namespace ApiClientCodeGen.VSIX.Extensibility.Commands;

[VisualStudioContribution]
public class GenerateNSwagCommand(TraceSource traceSource) : Command
{
    public override CommandConfiguration CommandConfiguration => new("%NSwagCommand.DisplayName%")
    {
        Icon = new(ImageMoniker.KnownValues.Extension, IconSettings.IconAndText),
        VisibleWhen = ActivationConstraint.ClientContext(ClientContextKey.Shell.ActiveSelectionFileName, ".(json|ya?ml|nswag)")
    };

    public override async Task ExecuteCommandAsync(IClientContext context, CancellationToken cancellationToken)
    {
        Logger.Instance.TrackFeatureUsage("Generate NSwag output");

        var inputFile = await context.GetInputFileAsync(cancellationToken);
        var namespaceName = await context.GetDefaultNamespaceAsync(cancellationToken);

        using var dependencyContext = new DependencyContext("NSwag");
        try
        {
            var documentFactory = new OpenApiDocumentFactory();
            var document = await documentFactory.GetDocumentAsync(inputFile);

            var generatorSettingsFactory = new NSwagCodeGeneratorSettingsFactory(
                namespaceName,
                new DefaultNSwagOptions());

            var generator = new CSharpClientGenerator(
                document,
                await GetGeneratorSettingsAsync(
                    inputFile,
                    document,
                    generatorSettingsFactory,
                    cancellationToken));

            var csharpCode = generator.GenerateFile();
            csharpCode = GeneratedCode.PrefixAutogeneratedCodeHeader(csharpCode, "NSwag", "v14.6.0");

            if (csharpCode is not null)
            {
                await File.WriteAllTextAsync(
                    OutputFile.GetOutputFilename(inputFile),
                    csharpCode,
                    cancellationToken);
            }
        }
        catch (Exception e)
        {
            traceSource.TraceEvent(
                TraceEventType.Error,
                0,
                "Error generating NSwag client code: {0}",
                e.Message);

            await this.WriteToOutputWindowAsync(
                "Error generating NSwag client code: " + e.Message,
                cancellationToken);
        }
        finally
        {
            dependencyContext.Succeeded();
        }
    }

    private static async Task<CSharpClientGeneratorSettings> GetGeneratorSettingsAsync(
        string inputFile,
        NSwag.OpenApiDocument document,
        NSwagCodeGeneratorSettingsFactory generatorSettingsFactory,
        CancellationToken cancellationToken)
    {
        CSharpClientGeneratorSettings settings;

        if (inputFile.EndsWith(".nswag", StringComparison.OrdinalIgnoreCase))
        {
            var nswagFileContent = await File.ReadAllTextAsync(inputFile, cancellationToken);
            var nswagFile = JsonSerializer.Deserialize<NSwagFile>(nswagFileContent, JsonSerializerOptions.Web)!;
            settings = nswagFile.CodeGenerators.OpenApiToCSharpClient
                ?? nswagFile.CodeGenerators.SwaggerToCSharpClient
                ?? throw new InvalidOperationException();
        }
        else
        {
            settings = generatorSettingsFactory.GetGeneratorSettings(document);
        }

        return settings;
    }

    class NSwagFile
    {
        public required CodeGenerators CodeGenerators { get; set; }
    }

    class CodeGenerators
    {
        public CSharpClientGeneratorSettings? SwaggerToCSharpClient { get; set; }
        public CSharpClientGeneratorSettings? OpenApiToCSharpClient { get; set; }
    }
}
