using Microsoft.VisualStudio.Extensibility;
using Microsoft.VisualStudio.Extensibility.Commands;
using NSwag.CodeGeneration.CSharp;
using Rapicgen.Core;
using Rapicgen.Core.Generators;
using Rapicgen.Core.Generators.NSwag;
using Rapicgen.Core.Logging;
using System.Diagnostics;
using System.Text.Json;
using ApiClientCodeGen.VSIX.Extensibility.Settings;
using ApiClientCodeGen.VSIX.Extensibility.Commands.Placements;

namespace ApiClientCodeGen.VSIX.Extensibility.Commands;

[VisualStudioContribution]
public class GenerateNSwagCommand(TraceSource traceSource, ExtensionSettingsProvider settingsProvider)
    : GenerateNSwagBaseCommand(traceSource, settingsProvider)
{
    public override CommandConfiguration CommandConfiguration => new("%NSwagCommand.DisplayName%")
    {
        Icon = new(ImageMoniker.KnownValues.Extension, IconSettings.IconAndText),
        VisibleWhen = ActivationConstraint.ClientContext(
            ClientContextKey.Shell.ActiveSelectionFileName, 
            ".(json|ya?ml)")
    };

    public override async Task ExecuteCommandAsync(
        IClientContext context,
        CancellationToken cancellationToken) =>
        await GenerateAsync(
            await context.GetInputFileAsync(cancellationToken),
            await context.GetDefaultNamespaceAsync(cancellationToken),
            cancellationToken);
}

[VisualStudioContribution]
public class GenerateNSwagStudioCommand(TraceSource traceSource, ExtensionSettingsProvider settingsProvider)
    : GenerateNSwagBaseCommand(traceSource, settingsProvider)
{
    public override CommandConfiguration CommandConfiguration => new("%NSwagStudioCommand.DisplayName%")
    {
        Icon = new(ImageMoniker.KnownValues.Extension, IconSettings.IconAndText),
        Placements = [KnownPlacements.Node_IncludeExcludeGroup],
        VisibleWhen = ActivationConstraint.ClientContext(
            ClientContextKey.Shell.ActiveSelectionFileName,
            ".(nswag)")
    };

    public override async Task ExecuteCommandAsync(
        IClientContext context,
        CancellationToken cancellationToken) =>
        await GenerateAsync(
            await context.GetInputFileAsync(cancellationToken),
            await context.GetDefaultNamespaceAsync(cancellationToken),
            cancellationToken);
}

[VisualStudioContribution]
public class GenerateNSwagNewCommand(TraceSource traceSource, ExtensionSettingsProvider settingsProvider)
    : GenerateNSwagBaseCommand(traceSource, settingsProvider)
{
    public override CommandConfiguration CommandConfiguration => new("%NSwagCommand.DisplayName%")
    {
        Icon = new(ImageMoniker.KnownValues.Extension, IconSettings.IconAndText),
    };

    public override async Task ExecuteCommandAsync(
        IClientContext context,
        CancellationToken cancellationToken) =>
        await GenerateAsync(
            await this.AddNewOpenApiFileAsync(context, cancellationToken),
            await context.GetDefaultNamespaceAsync(cancellationToken),
            cancellationToken);
}

public abstract class GenerateNSwagBaseCommand(TraceSource traceSource, ExtensionSettingsProvider settingsProvider) : Command
{
    private readonly ExtensionSettingsProvider settingsProvider = settingsProvider;

    public async Task GenerateAsync(
        string? inputFile,
        string defaultNamespace,
        CancellationToken cancellationToken)
    {
        Logger.Instance.WriteLine($"Starting NSwag code generation for: {inputFile}");
        
        if (inputFile == null)
        {
            Logger.Instance.WriteLine("No input file specified");
            return;
        }

        Logger.Instance.TrackFeatureUsage("Generate NSwag output");

        using var dependencyContext = new DependencyContext("NSwag");
        try
        {
            Logger.Instance.WriteLine("Loading OpenAPI specification...");
            var documentFactory = new OpenApiDocumentFactory();
            var document = await documentFactory.GetDocumentAsync(inputFile);

            Logger.Instance.WriteLine("Loading NSwag configuration...");
            var nswagOptions = await settingsProvider.GetNSwagOptionsAsync(cancellationToken);
            
            var generatorSettingsFactory = new NSwagCodeGeneratorSettingsFactory(
                defaultNamespace,
                nswagOptions);

            Logger.Instance.WriteLine("Initializing NSwag code generator...");
            var generator = new CSharpClientGenerator(
                document,
                await GetGeneratorSettingsAsync(
                    inputFile,
                    document,
                    generatorSettingsFactory,
                    cancellationToken));

            Logger.Instance.WriteLine("Generating C# client code...");
            var csharpCode = generator.GenerateFile();
            csharpCode = GeneratedCode.PrefixAutogeneratedCodeHeader(csharpCode, "NSwag", "v14.6.0");

            if (csharpCode is not null)
            {
                var outputFile = OutputFile.GetOutputFilename(inputFile);
                Logger.Instance.WriteLine($"Writing generated code to: {outputFile}");
                await File.WriteAllTextAsync(
                    outputFile,
                    csharpCode,
                    cancellationToken);
                Logger.Instance.WriteLine("NSwag code generation completed successfully");
            }
        }
        catch (Exception e)
        {
            Logger.Instance.WriteLine($"NSwag code generation failed: {e.Message}");
            traceSource.TraceEvent(
                TraceEventType.Error,
                0,
                "Error generating NSwag client code: {0}",
                e.Message);

            Logger.Instance.WriteLine("Error generating NSwag client code: " + e.Message);
        }
        finally
        {
            dependencyContext.Succeeded();
        }
    }

    private static async Task<CSharpClientGeneratorSettings> GetGeneratorSettingsAsync(
        string inputFile,
        NSwag.OpenApiDocument document,
        NSwagCodeGeneratorSettingsFactory generatorSettingsFactory,
        CancellationToken cancellationToken)
    {
        CSharpClientGeneratorSettings settings;

        if (inputFile.EndsWith(".nswag", StringComparison.OrdinalIgnoreCase))
        {
            var nswagFileContent = await File.ReadAllTextAsync(inputFile, cancellationToken);
            var nswagFile = JsonSerializer.Deserialize<NSwagFile>(nswagFileContent, JsonSerializerOptions.Web)!;
            settings = nswagFile.CodeGenerators.OpenApiToCSharpClient
                ?? nswagFile.CodeGenerators.SwaggerToCSharpClient
                ?? throw new InvalidOperationException();
        }
        else
        {
            settings = generatorSettingsFactory.GetGeneratorSettings(document);
        }

        return settings;
    }

    class NSwagFile
    {
        public required CodeGenerators CodeGenerators { get; set; }
    }

    class CodeGenerators
    {
        public CSharpClientGeneratorSettings? SwaggerToCSharpClient { get; set; }
        public CSharpClientGeneratorSettings? OpenApiToCSharpClient { get; set; }
    }
}
