#pragma warning disable VSEXTPREVIEW_SETTINGS
using ApiClientCodeGen.VSIX.Extensibility.Settings;
using Microsoft.VisualStudio.Extensibility;
using Microsoft.VisualStudio.Extensibility.Settings;
using Rapicgen.Core.External;
using Rapicgen.Core.Generators.Kiota;
using Rapicgen.Core.Logging;
using Rapicgen.Core.Options.AutoRest;
using Rapicgen.Core.Options.General;
using Rapicgen.Core.Options.Kiota;
using Rapicgen.Core.Options.NSwag;
using Rapicgen.Core.Options.NSwagStudio;
using Rapicgen.Core.Options.OpenApiGenerator;
using Rapicgen.Core.Options.Refitter;

namespace ApiClientCodeGen.VSIX.Extensibility;

public class ExtensionSettingsProvider(VisualStudioExtensibility extensibility)
{
    public async Task<IGeneralOptions> GetGeneralOptionsAsync(CancellationToken cancellationToken)
    {
        var values = await ReadAsync(
        [
            GeneralSettings.JavaPath,
            GeneralSettings.NpmPath,
            GeneralSettings.NSwagPath,
            GeneralSettings.SwaggerCodegenPath,
            GeneralSettings.OpenApiGeneratorPath,
            GeneralSettings.InstallMissingPackages
        ],
        cancellationToken);

        return new GeneralOptions(values);
    }

    public async Task<IAutoRestOptions> GetAutoRestOptionsAsync(CancellationToken cancellationToken)
    {
        var values = await ReadAsync(
        [
            AutoRestSettings.AutoRestAddCredentials,
            AutoRestSettings.AutoRestOverrideClientName,
            AutoRestSettings.AutoRestUseInternalConstructors,
            AutoRestSettings.AutoRestSyncMethods,
            AutoRestSettings.AutoRestUseDateTimeOffset,
            AutoRestSettings.AutoRestClientSideValidation
        ],
        cancellationToken);

        return new AutoRestOptions(values);
    }

    public async Task<INSwagOptions> GetNSwagOptionsAsync(CancellationToken cancellationToken)
    {
        var values = await ReadAsync(
        [
            NSwagSettings.NSwagInjectHttpClient,
            NSwagSettings.NSwagGenerateClientInterfaces,
            NSwagSettings.NSwagGenerateDtoTypes,
            NSwagSettings.NSwagClassStyle,
            NSwagSettings.NSwagUseDocumentTitle,
            NSwagSettings.NSwagParameterDateTimeFormat,
            NSwagSettings.NSwagUseBaseUrl
        ],
        cancellationToken);

        return new NSwagOptions(values);
    }

    public async Task<INSwagStudioOptions> GetNSwagStudioOptionsAsync(CancellationToken cancellationToken)
    {
        var values = await ReadAsync(
        [
            NSwagStudioSettings.NSwagStudioInjectHttpClient,
            NSwagStudioSettings.NSwagStudioGenerateClientInterfaces,
            NSwagStudioSettings.NSwagStudioGenerateDtoTypes,
            NSwagStudioSettings.NSwagStudioClassStyle,
            NSwagStudioSettings.NSwagStudioUseDocumentTitle,
            NSwagStudioSettings.NSwagStudioParameterDateTimeFormat,
            NSwagStudioSettings.NSwagStudioUseBaseUrl,
            NSwagStudioSettings.NSwagStudioGenerateResponseClasses,
            NSwagStudioSettings.NSwagStudioGenerateJsonMethods,
            NSwagStudioSettings.NSwagStudioRequiredPropertiesMustBeDefined,
            NSwagStudioSettings.NSwagStudioGenerateDefaultValues,
            NSwagStudioSettings.NSwagStudioGenerateDataAnnotations
        ],
        cancellationToken);

        return new NSwagStudioOptions(values);
    }

    public async Task<IOpenApiGeneratorOptions> GetOpenApiGeneratorOptionsAsync(CancellationToken cancellationToken)
    {
        var values = await ReadAsync(
        [
            OpenApiGeneratorSettings.OpenApiEmitDefaultValue,
            OpenApiGeneratorSettings.OpenApiMethodArgument,
            OpenApiGeneratorSettings.OpenApiGeneratePropertyChanged,
            OpenApiGeneratorSettings.OpenApiUseCollection,
            OpenApiGeneratorSettings.OpenApiUseDateTimeOffset,
            OpenApiGeneratorSettings.OpenApiTargetFramework,
            OpenApiGeneratorSettings.OpenApiCustomAdditionalProperties,
            OpenApiGeneratorSettings.OpenApiSkipFormModel,
            OpenApiGeneratorSettings.OpenApiTemplatesPath,
            OpenApiGeneratorSettings.OpenApiUseConfigurationFile,
            OpenApiGeneratorSettings.OpenApiGenerateMultipleFiles,
            OpenApiGeneratorSettings.OpenApiVersion,
            OpenApiGeneratorSettings.OpenApiHttpUserAgent
        ],
        cancellationToken);

        return new OpenApiOptions(values);
    }

    public async Task<IRefitterOptions> GetRefitterOptionsAsync(CancellationToken cancellationToken)
    {
        var values = await ReadAsync(
        [
            RefitterSettings.RefitterGenerateContracts,
            RefitterSettings.RefitterGenerateXmlDocCodeComments,
            RefitterSettings.RefitterAddAutoGeneratedHeader,
            RefitterSettings.RefitterReturnIApiResponse,
            RefitterSettings.RefitterGenerateInternalTypes,
            RefitterSettings.RefitterUseCancellationTokens,
            RefitterSettings.RefitterGenerateHeaderParameters,
            RefitterSettings.RefitterGenerateMultipleFiles
        ],
        cancellationToken);

        return new RefitterOptions(values);
    }

    public async Task<IKiotaOptions> GetKiotaOptionsAsync(CancellationToken cancellationToken)
    {
        var values = await ReadAsync(
        [
            KiotaSettings.KiotaGenerateMultipleFiles,
            KiotaSettings.KiotaTypeAccessModifier,
            KiotaSettings.KiotaUsesBackingStore
        ],
        cancellationToken);

        return new KiotaOptions(values);
    }

    public async Task<ITelemetryOptions> GetTelemetryOptionsAsync(CancellationToken cancellationToken)
    {
        var values = await ReadAsync(
        [
            AnalyticsSettings.TelemetryOptOut
        ],
        cancellationToken);

        return new TelemetryOptions(values, extensibility);
    }

    private async Task<SettingValues> ReadAsync(IReadOnlyCollection<Setting> settings, CancellationToken cancellationToken)
        => await extensibility.Settings().ReadEffectiveValuesAsync(settings, cancellationToken);

    private sealed class GeneralOptions(SettingValues values) : IGeneralOptions
    {
        public string JavaPath => Resolve(values.ValueOrDefault(GeneralSettings.JavaPath, string.Empty), PathProvider.GetInstalledJavaPath());
        public string NpmPath => Resolve(values.ValueOrDefault(GeneralSettings.NpmPath, string.Empty), PathProvider.GetNpmPath());
        public string NSwagPath => Resolve(values.ValueOrDefault(GeneralSettings.NSwagPath, string.Empty), PathProvider.GetNSwagStudioPath());
        public string SwaggerCodegenPath => Resolve(values.ValueOrDefault(GeneralSettings.SwaggerCodegenPath, string.Empty), PathProvider.GetSwaggerCodegenPath());
        public string OpenApiGeneratorPath => Resolve(values.ValueOrDefault(GeneralSettings.OpenApiGeneratorPath, string.Empty), PathProvider.GetOpenApiGeneratorPath());
        public bool? InstallMissingPackages => values.ValueOrDefault(GeneralSettings.InstallMissingPackages, true);
    }

    private sealed class AutoRestOptions(SettingValues values) : IAutoRestOptions
    {
        public bool AddCredentials => values.ValueOrDefault(AutoRestSettings.AutoRestAddCredentials, false);
        public bool OverrideClientName => values.ValueOrDefault(AutoRestSettings.AutoRestOverrideClientName, false);
        public bool UseInternalConstructors => values.ValueOrDefault(AutoRestSettings.AutoRestUseInternalConstructors, false);
        public SyncMethodOptions SyncMethods => ParseEnum(values.ValueOrDefault(AutoRestSettings.AutoRestSyncMethods, SyncMethodOptions.Essential.ToString()), SyncMethodOptions.Essential);
        public bool UseDateTimeOffset => values.ValueOrDefault(AutoRestSettings.AutoRestUseDateTimeOffset, false);
        public bool ClientSideValidation => values.ValueOrDefault(AutoRestSettings.AutoRestClientSideValidation, true);
    }

    private sealed class NSwagOptions(SettingValues values) : INSwagOptions
    {
        public bool InjectHttpClient => values.ValueOrDefault(NSwagSettings.NSwagInjectHttpClient, true);
        public bool GenerateClientInterfaces => values.ValueOrDefault(NSwagSettings.NSwagGenerateClientInterfaces, true);
        public bool GenerateDtoTypes => values.ValueOrDefault(NSwagSettings.NSwagGenerateDtoTypes, true);
        public CSharpClassStyle ClassStyle => ParseEnum(values.ValueOrDefault(NSwagSettings.NSwagClassStyle, CSharpClassStyle.Poco.ToString()), CSharpClassStyle.Poco);
        public bool UseDocumentTitle => values.ValueOrDefault(NSwagSettings.NSwagUseDocumentTitle, true);
        public string ParameterDateTimeFormat => values.ValueOrDefault(NSwagSettings.NSwagParameterDateTimeFormat, "s") ?? "s";
        public bool UseBaseUrl => values.ValueOrDefault(NSwagSettings.NSwagUseBaseUrl, false);
    }

    private sealed class NSwagStudioOptions(SettingValues values) : INSwagStudioOptions
    {
        public bool InjectHttpClient => values.ValueOrDefault(NSwagStudioSettings.NSwagStudioInjectHttpClient, true);
        public bool GenerateClientInterfaces => values.ValueOrDefault(NSwagStudioSettings.NSwagStudioGenerateClientInterfaces, true);
        public bool GenerateDtoTypes => values.ValueOrDefault(NSwagStudioSettings.NSwagStudioGenerateDtoTypes, true);
        public CSharpClassStyle ClassStyle => ParseEnum(values.ValueOrDefault(NSwagStudioSettings.NSwagStudioClassStyle, CSharpClassStyle.Poco.ToString()), CSharpClassStyle.Poco);
        public bool UseDocumentTitle => values.ValueOrDefault(NSwagStudioSettings.NSwagStudioUseDocumentTitle, true);
        public string ParameterDateTimeFormat => values.ValueOrDefault(NSwagStudioSettings.NSwagStudioParameterDateTimeFormat, "s") ?? "s";
        public bool UseBaseUrl => values.ValueOrDefault(NSwagStudioSettings.NSwagStudioUseBaseUrl, false);
        public bool GenerateResponseClasses => values.ValueOrDefault(NSwagStudioSettings.NSwagStudioGenerateResponseClasses, true);
        public bool GenerateJsonMethods => values.ValueOrDefault(NSwagStudioSettings.NSwagStudioGenerateJsonMethods, true);
        public bool RequiredPropertiesMustBeDefined => values.ValueOrDefault(NSwagStudioSettings.NSwagStudioRequiredPropertiesMustBeDefined, true);
        public bool GenerateDefaultValues => values.ValueOrDefault(NSwagStudioSettings.NSwagStudioGenerateDefaultValues, true);
        public bool GenerateDataAnnotations => values.ValueOrDefault(NSwagStudioSettings.NSwagStudioGenerateDataAnnotations, true);
    }

    private sealed class OpenApiOptions(SettingValues values) : IOpenApiGeneratorOptions
    {
        public bool EmitDefaultValue { get; set; } = values.ValueOrDefault(OpenApiGeneratorSettings.OpenApiEmitDefaultValue, true);
        public bool MethodArgument { get; set; } = values.ValueOrDefault(OpenApiGeneratorSettings.OpenApiMethodArgument, true);
        public bool GeneratePropertyChanged { get; set; } = values.ValueOrDefault(OpenApiGeneratorSettings.OpenApiGeneratePropertyChanged, false);
        public bool UseCollection { get; set; } = values.ValueOrDefault(OpenApiGeneratorSettings.OpenApiUseCollection, false);
        public bool UseDateTimeOffset { get; set; } = values.ValueOrDefault(OpenApiGeneratorSettings.OpenApiUseDateTimeOffset, false);
        public OpenApiSupportedTargetFramework TargetFramework { get; set; }
            = ParseEnum(values.ValueOrDefault(OpenApiGeneratorSettings.OpenApiTargetFramework, OpenApiSupportedTargetFramework.NetStandard21.ToString()), OpenApiSupportedTargetFramework.NetStandard21);
        public string? CustomAdditionalProperties { get; set; }
            = NormalizeEmpty(values.ValueOrDefault(OpenApiGeneratorSettings.OpenApiCustomAdditionalProperties, string.Empty));
        public bool SkipFormModel { get; set; } = values.ValueOrDefault(OpenApiGeneratorSettings.OpenApiSkipFormModel, true);
        public string? TemplatesPath { get; set; } = NormalizeEmpty(values.ValueOrDefault(OpenApiGeneratorSettings.OpenApiTemplatesPath, string.Empty));
        public bool UseConfigurationFile { get; set; } = values.ValueOrDefault(OpenApiGeneratorSettings.OpenApiUseConfigurationFile, true);
        public bool GenerateMultipleFiles { get; set; } = values.ValueOrDefault(OpenApiGeneratorSettings.OpenApiGenerateMultipleFiles, false);
        public OpenApiSupportedVersion Version { get; set; }
            = ParseEnum(values.ValueOrDefault(OpenApiGeneratorSettings.OpenApiVersion, OpenApiSupportedVersion.Latest.ToString()), OpenApiSupportedVersion.Latest);
        public string? HttpUserAgent { get; set; } = NormalizeEmpty(values.ValueOrDefault(OpenApiGeneratorSettings.OpenApiHttpUserAgent, string.Empty));
    }

    private sealed class RefitterOptions(SettingValues values) : IRefitterOptions
    {
        public bool GenerateContracts { get; set; } = values.ValueOrDefault(RefitterSettings.RefitterGenerateContracts, true);
        public bool GenerateXmlDocCodeComments { get; set; } = values.ValueOrDefault(RefitterSettings.RefitterGenerateXmlDocCodeComments, true);
        public bool AddAutoGeneratedHeader { get; set; } = values.ValueOrDefault(RefitterSettings.RefitterAddAutoGeneratedHeader, false);
        public bool ReturnIApiResponse { get; set; } = values.ValueOrDefault(RefitterSettings.RefitterReturnIApiResponse, false);
        public bool GenerateInternalTypes { get; set; } = values.ValueOrDefault(RefitterSettings.RefitterGenerateInternalTypes, false);
        public bool UseCancellationTokens { get; set; } = values.ValueOrDefault(RefitterSettings.RefitterUseCancellationTokens, false);
        public bool GenerateHeaderParameters { get; set; } = values.ValueOrDefault(RefitterSettings.RefitterGenerateHeaderParameters, true);
        public bool GenerateMultipleFiles { get; set; } = values.ValueOrDefault(RefitterSettings.RefitterGenerateMultipleFiles, false);
    }

    private sealed class KiotaOptions(SettingValues values) : IKiotaOptions
    {
        public bool GenerateMultipleFiles => values.ValueOrDefault(KiotaSettings.KiotaGenerateMultipleFiles, false);
        public TypeAccessModifier TypeAccessModifier => ParseEnum(values.ValueOrDefault(KiotaSettings.KiotaTypeAccessModifier, TypeAccessModifier.Public.ToString()), TypeAccessModifier.Public);
        public bool UsesBackingStore => values.ValueOrDefault(KiotaSettings.KiotaUsesBackingStore, false);
    }

    private sealed class TelemetryOptions(SettingValues values, VisualStudioExtensibility extensibility) : ITelemetryOptions
    {
        public bool TelemetryOptOut
        {
            get => values.ValueOrDefault(AnalyticsSettings.TelemetryOptOut, false);
            set => _ = extensibility.Settings().WriteAsync(
            batch => batch.WriteSetting(AnalyticsSettings.TelemetryOptOut, value),
            description: "Update telemetry preference",
            CancellationToken.None);
        }
    }

    private static T ParseEnum<T>(string? raw, T fallback)
        where T : struct
        => Enum.TryParse(raw, out T parsed) ? parsed : fallback;

    private static string? NormalizeEmpty(string? value)
        => string.IsNullOrWhiteSpace(value) ? null : value;

    private static string Resolve(string? value, string defaultValue)
        => string.IsNullOrWhiteSpace(value) ? defaultValue : value;
}
#pragma warning restore VSEXTPREVIEW_SETTINGS
