#pragma warning disable VSEXTPREVIEW_SETTINGS
using ApiClientCodeGen.VSIX.Extensibility.Settings;
using Microsoft.VisualStudio.Extensibility;
using Microsoft.VisualStudio.Extensibility.Settings;
using Rapicgen.Core.External;
using Rapicgen.Core.Generators.Kiota;
using Rapicgen.Core.Logging;
using Rapicgen.Core.Options.AutoRest;
using Rapicgen.Core.Options.General;
using Rapicgen.Core.Options.Kiota;
using Rapicgen.Core.Options.NSwag;
using Rapicgen.Core.Options.NSwagStudio;
using Rapicgen.Core.Options.OpenApiGenerator;
using Rapicgen.Core.Options.Refitter;

namespace ApiClientCodeGen.VSIX.Extensibility;

public class ExtensionSettingsProvider(VisualStudioExtensibility extensibility)
{
    public async Task<IGeneralOptions> GetGeneralOptionsAsync(CancellationToken cancellationToken)
    {
        var values = await ReadAsync(
        [
            SettingDefinitions.JavaPath,
            SettingDefinitions.NpmPath,
            SettingDefinitions.NSwagPath,
            SettingDefinitions.SwaggerCodegenPath,
            SettingDefinitions.OpenApiGeneratorPath,
            SettingDefinitions.InstallMissingPackages
        ],
        cancellationToken);

        return new GeneralOptions(values);
    }

    public async Task<IAutoRestOptions> GetAutoRestOptionsAsync(CancellationToken cancellationToken)
    {
        var values = await ReadAsync(
        [
            SettingDefinitions.AutoRestAddCredentials,
            SettingDefinitions.AutoRestOverrideClientName,
            SettingDefinitions.AutoRestUseInternalConstructors,
            SettingDefinitions.AutoRestSyncMethods,
            SettingDefinitions.AutoRestUseDateTimeOffset,
            SettingDefinitions.AutoRestClientSideValidation
        ],
        cancellationToken);

        return new AutoRestOptions(values);
    }

    public async Task<INSwagOptions> GetNSwagOptionsAsync(CancellationToken cancellationToken)
    {
        var values = await ReadAsync(
        [
            SettingDefinitions.NSwagInjectHttpClient,
            SettingDefinitions.NSwagGenerateClientInterfaces,
            SettingDefinitions.NSwagGenerateDtoTypes,
            SettingDefinitions.NSwagClassStyle,
            SettingDefinitions.NSwagUseDocumentTitle,
            SettingDefinitions.NSwagParameterDateTimeFormat,
            SettingDefinitions.NSwagUseBaseUrl
        ],
        cancellationToken);

        return new NSwagOptions(values);
    }

    public async Task<INSwagStudioOptions> GetNSwagStudioOptionsAsync(CancellationToken cancellationToken)
    {
        var values = await ReadAsync(
        [
            SettingDefinitions.NSwagStudioInjectHttpClient,
            SettingDefinitions.NSwagStudioGenerateClientInterfaces,
            SettingDefinitions.NSwagStudioGenerateDtoTypes,
            SettingDefinitions.NSwagStudioClassStyle,
            SettingDefinitions.NSwagStudioUseDocumentTitle,
            SettingDefinitions.NSwagStudioParameterDateTimeFormat,
            SettingDefinitions.NSwagStudioUseBaseUrl,
            SettingDefinitions.NSwagStudioGenerateResponseClasses,
            SettingDefinitions.NSwagStudioGenerateJsonMethods,
            SettingDefinitions.NSwagStudioRequiredPropertiesMustBeDefined,
            SettingDefinitions.NSwagStudioGenerateDefaultValues,
            SettingDefinitions.NSwagStudioGenerateDataAnnotations
        ],
        cancellationToken);

        return new NSwagStudioOptions(values);
    }

    public async Task<IOpenApiGeneratorOptions> GetOpenApiGeneratorOptionsAsync(CancellationToken cancellationToken)
    {
        var values = await ReadAsync(
        [
            SettingDefinitions.OpenApiEmitDefaultValue,
            SettingDefinitions.OpenApiMethodArgument,
            SettingDefinitions.OpenApiGeneratePropertyChanged,
            SettingDefinitions.OpenApiUseCollection,
            SettingDefinitions.OpenApiUseDateTimeOffset,
            SettingDefinitions.OpenApiTargetFramework,
            SettingDefinitions.OpenApiCustomAdditionalProperties,
            SettingDefinitions.OpenApiSkipFormModel,
            SettingDefinitions.OpenApiTemplatesPath,
            SettingDefinitions.OpenApiUseConfigurationFile,
            SettingDefinitions.OpenApiGenerateMultipleFiles,
            SettingDefinitions.OpenApiVersion,
            SettingDefinitions.OpenApiHttpUserAgent
        ],
        cancellationToken);

        return new OpenApiOptions(values);
    }

    public async Task<IRefitterOptions> GetRefitterOptionsAsync(CancellationToken cancellationToken)
    {
        var values = await ReadAsync(
        [
            SettingDefinitions.RefitterGenerateContracts,
            SettingDefinitions.RefitterGenerateXmlDocCodeComments,
            SettingDefinitions.RefitterAddAutoGeneratedHeader,
            SettingDefinitions.RefitterReturnIApiResponse,
            SettingDefinitions.RefitterGenerateInternalTypes,
            SettingDefinitions.RefitterUseCancellationTokens,
            SettingDefinitions.RefitterGenerateHeaderParameters,
            SettingDefinitions.RefitterGenerateMultipleFiles
        ],
        cancellationToken);

        return new RefitterOptions(values);
    }

    public async Task<IKiotaOptions> GetKiotaOptionsAsync(CancellationToken cancellationToken)
    {
        var values = await ReadAsync(
        [
            SettingDefinitions.KiotaGenerateMultipleFiles,
            SettingDefinitions.KiotaTypeAccessModifier,
            SettingDefinitions.KiotaUsesBackingStore
        ],
        cancellationToken);

        return new KiotaOptions(values);
    }

    public async Task<ITelemetryOptions> GetTelemetryOptionsAsync(CancellationToken cancellationToken)
    {
        var values = await ReadAsync(
        [
            SettingDefinitions.TelemetryOptOut
        ],
        cancellationToken);

        return new TelemetryOptions(values, extensibility);
    }

    private async Task<SettingValues> ReadAsync(IReadOnlyCollection<Setting> settings, CancellationToken cancellationToken)
        => await extensibility.Settings().ReadEffectiveValuesAsync(settings, cancellationToken);

    private sealed class GeneralOptions(SettingValues values) : IGeneralOptions
    {
        public string JavaPath => Resolve(values.ValueOrDefault(SettingDefinitions.JavaPath, string.Empty), PathProvider.GetInstalledJavaPath());
        public string NpmPath => Resolve(values.ValueOrDefault(SettingDefinitions.NpmPath, string.Empty), PathProvider.GetNpmPath());
        public string NSwagPath => Resolve(values.ValueOrDefault(SettingDefinitions.NSwagPath, string.Empty), PathProvider.GetNSwagStudioPath());
        public string SwaggerCodegenPath => Resolve(values.ValueOrDefault(SettingDefinitions.SwaggerCodegenPath, string.Empty), PathProvider.GetSwaggerCodegenPath());
        public string OpenApiGeneratorPath => Resolve(values.ValueOrDefault(SettingDefinitions.OpenApiGeneratorPath, string.Empty), PathProvider.GetOpenApiGeneratorPath());
        public bool? InstallMissingPackages => values.ValueOrDefault(SettingDefinitions.InstallMissingPackages, true);
    }

    private sealed class AutoRestOptions(SettingValues values) : IAutoRestOptions
    {
        public bool AddCredentials => values.ValueOrDefault(SettingDefinitions.AutoRestAddCredentials, false);
        public bool OverrideClientName => values.ValueOrDefault(SettingDefinitions.AutoRestOverrideClientName, false);
        public bool UseInternalConstructors => values.ValueOrDefault(SettingDefinitions.AutoRestUseInternalConstructors, false);
        public SyncMethodOptions SyncMethods => ParseEnum(values.ValueOrDefault(SettingDefinitions.AutoRestSyncMethods, SyncMethodOptions.Essential.ToString()), SyncMethodOptions.Essential);
        public bool UseDateTimeOffset => values.ValueOrDefault(SettingDefinitions.AutoRestUseDateTimeOffset, false);
        public bool ClientSideValidation => values.ValueOrDefault(SettingDefinitions.AutoRestClientSideValidation, true);
    }

    private sealed class NSwagOptions(SettingValues values) : INSwagOptions
    {
        public bool InjectHttpClient => values.ValueOrDefault(SettingDefinitions.NSwagInjectHttpClient, true);
        public bool GenerateClientInterfaces => values.ValueOrDefault(SettingDefinitions.NSwagGenerateClientInterfaces, true);
        public bool GenerateDtoTypes => values.ValueOrDefault(SettingDefinitions.NSwagGenerateDtoTypes, true);
        public CSharpClassStyle ClassStyle => ParseEnum(values.ValueOrDefault(SettingDefinitions.NSwagClassStyle, CSharpClassStyle.Poco.ToString()), CSharpClassStyle.Poco);
        public bool UseDocumentTitle => values.ValueOrDefault(SettingDefinitions.NSwagUseDocumentTitle, true);
        public string ParameterDateTimeFormat => values.ValueOrDefault(SettingDefinitions.NSwagParameterDateTimeFormat, "s") ?? "s";
        public bool UseBaseUrl => values.ValueOrDefault(SettingDefinitions.NSwagUseBaseUrl, false);
    }

    private sealed class NSwagStudioOptions(SettingValues values) : INSwagStudioOptions
    {
        public bool InjectHttpClient => values.ValueOrDefault(SettingDefinitions.NSwagStudioInjectHttpClient, true);
        public bool GenerateClientInterfaces => values.ValueOrDefault(SettingDefinitions.NSwagStudioGenerateClientInterfaces, true);
        public bool GenerateDtoTypes => values.ValueOrDefault(SettingDefinitions.NSwagStudioGenerateDtoTypes, true);
        public CSharpClassStyle ClassStyle => ParseEnum(values.ValueOrDefault(SettingDefinitions.NSwagStudioClassStyle, CSharpClassStyle.Poco.ToString()), CSharpClassStyle.Poco);
        public bool UseDocumentTitle => values.ValueOrDefault(SettingDefinitions.NSwagStudioUseDocumentTitle, true);
        public string ParameterDateTimeFormat => values.ValueOrDefault(SettingDefinitions.NSwagStudioParameterDateTimeFormat, "s") ?? "s";
        public bool UseBaseUrl => values.ValueOrDefault(SettingDefinitions.NSwagStudioUseBaseUrl, false);
        public bool GenerateResponseClasses => values.ValueOrDefault(SettingDefinitions.NSwagStudioGenerateResponseClasses, true);
        public bool GenerateJsonMethods => values.ValueOrDefault(SettingDefinitions.NSwagStudioGenerateJsonMethods, true);
        public bool RequiredPropertiesMustBeDefined => values.ValueOrDefault(SettingDefinitions.NSwagStudioRequiredPropertiesMustBeDefined, true);
        public bool GenerateDefaultValues => values.ValueOrDefault(SettingDefinitions.NSwagStudioGenerateDefaultValues, true);
        public bool GenerateDataAnnotations => values.ValueOrDefault(SettingDefinitions.NSwagStudioGenerateDataAnnotations, true);
    }

    private sealed class OpenApiOptions(SettingValues values) : IOpenApiGeneratorOptions
    {
        public bool EmitDefaultValue { get; set; } = values.ValueOrDefault(SettingDefinitions.OpenApiEmitDefaultValue, true);
        public bool MethodArgument { get; set; } = values.ValueOrDefault(SettingDefinitions.OpenApiMethodArgument, true);
        public bool GeneratePropertyChanged { get; set; } = values.ValueOrDefault(SettingDefinitions.OpenApiGeneratePropertyChanged, false);
        public bool UseCollection { get; set; } = values.ValueOrDefault(SettingDefinitions.OpenApiUseCollection, false);
        public bool UseDateTimeOffset { get; set; } = values.ValueOrDefault(SettingDefinitions.OpenApiUseDateTimeOffset, false);
        public OpenApiSupportedTargetFramework TargetFramework { get; set; }
            = ParseEnum(values.ValueOrDefault(SettingDefinitions.OpenApiTargetFramework, OpenApiSupportedTargetFramework.NetStandard21.ToString()), OpenApiSupportedTargetFramework.NetStandard21);
        public string? CustomAdditionalProperties { get; set; }
            = NormalizeEmpty(values.ValueOrDefault(SettingDefinitions.OpenApiCustomAdditionalProperties, string.Empty));
        public bool SkipFormModel { get; set; } = values.ValueOrDefault(SettingDefinitions.OpenApiSkipFormModel, true);
        public string? TemplatesPath { get; set; } = NormalizeEmpty(values.ValueOrDefault(SettingDefinitions.OpenApiTemplatesPath, string.Empty));
        public bool UseConfigurationFile { get; set; } = values.ValueOrDefault(SettingDefinitions.OpenApiUseConfigurationFile, true);
        public bool GenerateMultipleFiles { get; set; } = values.ValueOrDefault(SettingDefinitions.OpenApiGenerateMultipleFiles, false);
        public OpenApiSupportedVersion Version { get; set; }
            = ParseEnum(values.ValueOrDefault(SettingDefinitions.OpenApiVersion, OpenApiSupportedVersion.Latest.ToString()), OpenApiSupportedVersion.Latest);
        public string? HttpUserAgent { get; set; } = NormalizeEmpty(values.ValueOrDefault(SettingDefinitions.OpenApiHttpUserAgent, string.Empty));
    }

    private sealed class RefitterOptions(SettingValues values) : IRefitterOptions
    {
        public bool GenerateContracts { get; set; } = values.ValueOrDefault(SettingDefinitions.RefitterGenerateContracts, true);
        public bool GenerateXmlDocCodeComments { get; set; } = values.ValueOrDefault(SettingDefinitions.RefitterGenerateXmlDocCodeComments, true);
        public bool AddAutoGeneratedHeader { get; set; } = values.ValueOrDefault(SettingDefinitions.RefitterAddAutoGeneratedHeader, false);
        public bool ReturnIApiResponse { get; set; } = values.ValueOrDefault(SettingDefinitions.RefitterReturnIApiResponse, false);
        public bool GenerateInternalTypes { get; set; } = values.ValueOrDefault(SettingDefinitions.RefitterGenerateInternalTypes, false);
        public bool UseCancellationTokens { get; set; } = values.ValueOrDefault(SettingDefinitions.RefitterUseCancellationTokens, false);
        public bool GenerateHeaderParameters { get; set; } = values.ValueOrDefault(SettingDefinitions.RefitterGenerateHeaderParameters, true);
        public bool GenerateMultipleFiles { get; set; } = values.ValueOrDefault(SettingDefinitions.RefitterGenerateMultipleFiles, false);
    }

    private sealed class KiotaOptions(SettingValues values) : IKiotaOptions
    {
        public bool GenerateMultipleFiles => values.ValueOrDefault(SettingDefinitions.KiotaGenerateMultipleFiles, false);
        public TypeAccessModifier TypeAccessModifier => ParseEnum(values.ValueOrDefault(SettingDefinitions.KiotaTypeAccessModifier, TypeAccessModifier.Public.ToString()), TypeAccessModifier.Public);
        public bool UsesBackingStore => values.ValueOrDefault(SettingDefinitions.KiotaUsesBackingStore, false);
    }

    private sealed class TelemetryOptions(SettingValues values, VisualStudioExtensibility extensibility) : ITelemetryOptions
    {
        public bool TelemetryOptOut
        {
            get => values.ValueOrDefault(SettingDefinitions.TelemetryOptOut, false);
            set => _ = extensibility.Settings().WriteAsync(
            batch => batch.WriteSetting(SettingDefinitions.TelemetryOptOut, value),
            description: "Update telemetry preference",
            CancellationToken.None);
        }
    }

    private static T ParseEnum<T>(string? raw, T fallback)
        where T : struct
        => Enum.TryParse(raw, out T parsed) ? parsed : fallback;

    private static string? NormalizeEmpty(string? value)
        => string.IsNullOrWhiteSpace(value) ? null : value;

    private static string Resolve(string? value, string defaultValue)
        => string.IsNullOrWhiteSpace(value) ? defaultValue : value;
}
#pragma warning restore VSEXTPREVIEW_SETTINGS
