#pragma warning disable VSEXTPREVIEW_SETTINGS
using Microsoft.VisualStudio.Extensibility;
using Microsoft.VisualStudio.Extensibility.Settings;

namespace ApiClientCodeGen.VSIX.Extensibility.Settings;

internal static class RefitterSettings
{
    [VisualStudioContribution]
    internal static SettingCategory RefitterCategory { get; } = new("refitter", "%Settings.Refitter.DisplayName%", SettingsRoot.RootCategory)
    {
        GenerateObserverClass = true,
        Order = 2,
    };

    [VisualStudioContribution]
    internal static Setting.Boolean RefitterGenerateContracts { get; } = new(
        "generateContracts",
        "%Settings.Refitter.GenerateContracts.DisplayName%",
        RefitterCategory,
        defaultValue: true)
    {
        Description = "%Settings.Refitter.GenerateContracts.Description%",
    };

    [VisualStudioContribution]
    internal static Setting.Boolean RefitterGenerateXmlDocCodeComments { get; } = new(
        "generateXmlDocCodeComments",
        "%Settings.Refitter.GenerateXmlDocCodeComments.DisplayName%",
        RefitterCategory,
        defaultValue: true)
    {
        Description = "%Settings.Refitter.GenerateXmlDocCodeComments.Description%",
    };

    [VisualStudioContribution]
    internal static Setting.Boolean RefitterAddAutoGeneratedHeader { get; } = new(
        "addAutoGeneratedHeader",
        "%Settings.Refitter.AddAutoGeneratedHeader.DisplayName%",
        RefitterCategory,
        defaultValue: false);

    [VisualStudioContribution]
    internal static Setting.Boolean RefitterReturnIApiResponse { get; } = new(
        "returnIApiResponse",
        "%Settings.Refitter.ReturnIApiResponse.DisplayName%",
        RefitterCategory,
        defaultValue: false)
    {
        Description = "%Settings.Refitter.ReturnIApiResponse.Description%",
    };

    [VisualStudioContribution]
    internal static Setting.Boolean RefitterGenerateInternalTypes { get; } = new(
        "generateInternalTypes",
        "%Settings.Refitter.GenerateInternalTypes.DisplayName%",
        RefitterCategory,
        defaultValue: false);

    [VisualStudioContribution]
    internal static Setting.Boolean RefitterUseCancellationTokens { get; } = new(
        "useCancellationTokens",
        "%Settings.Refitter.UseCancellationTokens.DisplayName%",
        RefitterCategory,
        defaultValue: false);

    [VisualStudioContribution]
    internal static Setting.Boolean RefitterGenerateHeaderParameters { get; } = new(
        "generateHeaderParameters",
        "%Settings.Refitter.GenerateHeaderParameters.DisplayName%",
        RefitterCategory,
        defaultValue: true);

    [VisualStudioContribution]
    internal static Setting.Boolean RefitterGenerateMultipleFiles { get; } = new(
        "generateMultipleFiles",
        "%Settings.Refitter.GenerateMultipleFiles.DisplayName%",
        RefitterCategory,
        defaultValue: false);
}
#pragma warning restore VSEXTPREVIEW_SETTINGS
