using System;
using System.IO;
using Rapicgen.Core.External;
using Rapicgen.Core.Installer;
using Rapicgen.Core.Options.Kiota;

namespace Rapicgen.Core.Generators.Kiota;

public class KiotaCodeGenerator(
    string swaggerFile,
    string defaultNamespace,
    IProcessLauncher processLauncher,
    IDependencyInstaller dependencyInstaller,
    IKiotaOptions options) : ICodeGenerator
{
    private const string KiotaLockFile = "kiota-lock.json";

    public string GenerateCode(IProgressReporter? pGenerateProgress)
    {
        pGenerateProgress?.Progress(10);
        dependencyInstaller.InstallKiota();

        string swaggerFilename = new FileInfo(swaggerFile).Name;
        if (swaggerFilename == KiotaLockFile)
        {
            pGenerateProgress?.Progress(40);
            var outputDirectory = Path.GetDirectoryName(swaggerFile)!;
            RunKiotaUpdate();

            pGenerateProgress?.Progress(80);
            var lockFileOutput = string.Empty;
            if (!options.GenerateMultipleFiles)
            {
                lockFileOutput = CSharpFileMerger.MergeFiles(outputDirectory);
            }

            pGenerateProgress?.Progress(100);
            return GeneratedCode.PrefixAutogeneratedCodeHeader(
                lockFileOutput,
                ExternalTools.Kiota.DisplayName,
                ExternalTools.Kiota.VersionLabel);
        }

        pGenerateProgress?.Progress(30);
        string outputFolder = options.GenerateMultipleFiles
            ? Path.GetDirectoryName(swaggerFile)
            : Path.Combine(Path.GetTempPath(), Guid.NewGuid().ToString());

        if (!Directory.Exists(outputFolder))
            Directory.CreateDirectory(outputFolder);

        pGenerateProgress?.Progress(40);
        RunKiotaGenerate(outputFolder);

        if (!options.GenerateMultipleFiles &&
            File.Exists(Path.Combine(Path.GetDirectoryName(swaggerFile)!, KiotaLockFile)))
        {
            File.Copy(
                swaggerFile,
                Path.Combine(outputFolder, swaggerFilename),
                true);

            File.Copy(
                Path.Combine(Path.GetDirectoryName(swaggerFile)!, KiotaLockFile),
                Path.Combine(outputFolder, KiotaLockFile),
                true);

            pGenerateProgress?.Progress(60);

            var arguments = $" update -o \"{outputFolder}\"";
            new ToolRunner(processLauncher).Run(
                ExternalTools.Kiota, PathProvider.GetKiotaPath(), arguments, outputFolder);
        }

        pGenerateProgress?.Progress(80);
        string output = string.Empty;

        if (!options.GenerateMultipleFiles)
        {
            output = CSharpFileMerger.MergeFiles(outputFolder);

            var kiotaConfigFile = Path.Combine(outputFolder, KiotaLockFile);
            if (File.Exists(kiotaConfigFile))
            {
                File.Copy(
                    kiotaConfigFile,
                    Path.Combine(Path.GetDirectoryName(swaggerFile)!, KiotaLockFile),
                    true);
            }
        }

        pGenerateProgress?.Progress(100);
        return GeneratedCode.PrefixAutogeneratedCodeHeader(
            output,
            ExternalTools.Kiota.DisplayName,
            ExternalTools.Kiota.VersionLabel);
    }

    private void RunKiotaGenerate(string outputFolder)
    {
        var arguments = $" generate " +
                        $"-l CSharp " +
                        $"-d \"{swaggerFile}\" " +
                        $"-o \"{outputFolder}\" " +
                        $"-n {defaultNamespace} " +
                        $"--type-access-modifier {options.TypeAccessModifier}";

        if (options.UsesBackingStore)
            arguments += " --backing-store";

        new ToolRunner(processLauncher).Run(
            ExternalTools.Kiota, PathProvider.GetKiotaPath(), arguments);
    }

    private void RunKiotaUpdate()
    {
        var arguments = $" update -o \"{Path.GetDirectoryName(swaggerFile)!}\"";
        new ToolRunner(processLauncher).Run(
            ExternalTools.Kiota, PathProvider.GetKiotaPath(), arguments);
    }
}
