using System;
using System.IO;
using Rapicgen.Core.Installer;
using Rapicgen.Core.Logging;
using Rapicgen.Core.Options.Kiota;

namespace Rapicgen.Core.Generators.Kiota;

public class KiotaCodeGenerator(
    string swaggerFile,
    string defaultNamespace,
    IProcessLauncher processLauncher,
    IDependencyInstaller dependencyInstaller,
    IKiotaOptions options) : ICodeGenerator
{
    private const string KiotaLockFile = "kiota-lock.json";

    public string GenerateCode(IProgressReporter? pGenerateProgress)
    {
        pGenerateProgress?.Progress(10);
        dependencyInstaller.InstallKiota();

        pGenerateProgress?.Progress(30);
        string outputFolder = options.GenerateMultipleFiles
            ? Path.GetDirectoryName(swaggerFile)
            : Path.Combine(Path.GetTempPath(), Guid.NewGuid().ToString());

        if (!Directory.Exists(outputFolder))
            Directory.CreateDirectory(outputFolder);

        pGenerateProgress?.Progress(40);
        const string command = "kiota";
        var arguments = $" generate -l CSharp -d \"{swaggerFile}\" -o \"{outputFolder}\" -n {defaultNamespace}";
        using var context = new DependencyContext("Kiota", $"{command} {arguments}");
        processLauncher.Start(command, arguments);
        context.Succeeded();

        if (!options.GenerateMultipleFiles &&
            File.Exists(Path.Combine(Path.GetDirectoryName(swaggerFile)!, KiotaLockFile)))
        {
            File.Copy(
                Path.Combine(Path.GetDirectoryName(swaggerFile)!, KiotaLockFile),
                Path.Combine(outputFolder, KiotaLockFile),
                true);

            pGenerateProgress?.Progress(60);
            arguments = $" update -o \"{outputFolder}\"";
            using var updateContext = new DependencyContext("Kiota", $"{command} {arguments}");
            processLauncher.Start(command, arguments);
            updateContext.Succeeded();
        }

        pGenerateProgress?.Progress(80);
        string output = string.Empty;

        if (!options.GenerateMultipleFiles)
        {
            output = CSharpFileMerger.MergeFiles(outputFolder);

            var kiotaConfigFile = Path.Combine(outputFolder, KiotaLockFile);
            if (File.Exists(kiotaConfigFile))
            {
                File.Copy(
                    kiotaConfigFile,
                    Path.Combine(Path.GetDirectoryName(swaggerFile)!, KiotaLockFile),
                    true);
            }
        }

        pGenerateProgress?.Progress(100);
        return GeneratedCode.PrefixAutogeneratedCodeHeader(
            output,
            "Kiota",
            "v1.14.0");
    }
}